spring:
  application:
    name: guardian-api

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:postgresql://localhost:5432/guardian_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: 8080

logging:
  level:
    com.guardianapp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

firebase:
  enabled: true
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:secrets/manto-app-ade75-firebase-adminsdk-fbsvc-7118566358.json}

google:
  drive:
    enabled: ${GOOGLE_DRIVE_ENABLED:false}
    service-account-path: ${GOOGLE_DRIVE_SERVICE_ACCOUNT_PATH:secrets/google-drive-service-account.json}
    folder-id: ${GOOGLE_DRIVE_FOLDER_ID:root}
